version: '3.5'
services:
  web:
    build: ./php-fpm
    ports:
      - 9000
    expose:
      - 9000
    volumes:
        - ./src:/application/
    env_file: .env.web
    networks:
      - whyjustrun
  webserver:
    image: nginx
    volumes:
        - ./src:/application/ # used for serving static files
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 3001:80
    links:
        - web
    networks:
      - whyjustrun
networks:
  whyjustrun:
    name: whyjustrun
    driver: bridge
